#!/usr/bin/perl -W

#
# KMTNet FWHM plotter
# leecu@kasi.re.kr (2018-02-20)
# 
# 18-02-15 temperature range [-1.5:-0.9]
#          zoomed sec z
#          day shift 23:00 00:00 01:00
# 18-04-27 display guess + focus
# 18-05-14 prevent dounle running
# 18-07-16 temperature range [-6.6:-4.8]
#

$doplotter = 1;

$pid = `ps -al | grep do-plotFWHM | wc | awk \'{print \$1}\'`;
chop $pid;

if ($pid gt 1) {
  print "already running -- $pid\n";
  exit;
}

if($doplotter ge 1){
   $dd = `date +"20%y-%m-%d"`;
   chop $dd;
   $fw = `date --date='-8 hours' +"fw%y%m%d.dat"`;
   chop $fw;
#   $st = `date +"%d:%H:%M:%S"`;
#   chop $st;
#
#   system "echo $st -1.01 -1.02 -1.03 -1.04 -5.00 16.0 1.0>> $fw";
#   sleep 1;
#   $st = `date +"%d:%H:%M:%S"`;
#   chop $st;
#
#   system "echo $st -1.04 -1.03 -1.02 -1.01 -5.00 16.0 1.0>> $fw";
   system "echo pause 10 > loop.plt";
   system "echo reset >> loop.plt";
   system "echo \"stats '$fw' u 7 nooutput \" >> loop.plt";
   system "echo set term x11 >> loop.plt";
   system "echo \"set title 'FFT (FWHM-FOCUS-TEMP) Monitoring' \" >> loop.plt"; 
   system "echo set xdata time >> loop.plt"; 
   system "echo \"set timefmt '%d:%H:%M:%S' \" >> loop.plt"; 
   system "echo \"set format x '%H:%M' \" >> loop.plt";
   system "echo set autoscale xfix >> loop.plt";
   system "echo set yrange [0:12] >> loop.plt";
   system "echo set y2tics >> loop.plt";
   system "echo set y2range [-6.6:-4.8] >> loop.plt";
#   system "echo set y2range [] >> loop.plt";
   system "echo set key left top >> loop.plt";
   system "echo \"set xlabel 'UT ($dd)' \" >> loop.plt";
   system "echo \"set ylabel 'FWHM (arcsec) / T (C)' \" >> loop.plt"; 
   system "echo \"set y2label 'FOCUS (mm)' \" >> loop.plt"; 
   system "echo set grid >> loop.plt";
   system "echo replot >> loop.plt";
   system "echo reread >> loop.plt";

   $cmd = "gnuplot46 -persist -e \'reset; stats \"$fw\" u 7 nooutput; ";
   $cmd = $cmd."set term x11; ";
   $cmd = $cmd."set title \"FFT (FWHM-FOCUS-TEMP) Monitoring\"; ";
   $cmd = $cmd."set xdata time; ";
   $cmd = $cmd."set timefmt \"%d:%H:%M:%S\"; ";
   $cmd = $cmd."set format x \"%H:%M\"; ";
   $cmd = $cmd."set autoscale xfix; ";
   $cmd = $cmd."set yrange [0:12]; ";
   $cmd = $cmd."set y2tics; ";
   $cmd = $cmd."set y2range [-6.6:-4.8]; ";
#   $cmd = $cmd."set y2range []; ";
   $cmd = $cmd."set key left top; ";
   $cmd = $cmd."set xlabel \"UT ($dd)\"; ";
   $cmd = $cmd."set ylabel \"FWHM (arcsec) / T (C)\"; ";
   $cmd = $cmd."set y2label \"FOCUS (mm)\"; ";
   $cmd = $cmd."set grid; ";
   $cmd = $cmd."plot ";
   $cmd = $cmd."\"$fw\" u 1:(\$7-STATS_median+6) pt 5 ps 2 lc rgb \"orange\" title \"dT\", ";
   $cmd = $cmd."\"$fw\" u 1:2 pt 4 ps 2 lc rgb \"red\" title \"N\", ";
   $cmd = $cmd."\"$fw\" u 1:3 pt 4 ps 2 lc rgb \"magenta\" title \"E\", ";
   $cmd = $cmd."\"$fw\" u 1:4 pt 4 ps 2 lc rgb \"green\" title \"W\", ";
   $cmd = $cmd."\"$fw\" u 1:5 pt 4 ps 2 lc rgb \"blue\" title \"S\", ";
   $cmd = $cmd."\"$fw\" u 1:((\$8-1)*10) pt 7 ps 2 lc rgb \"red\" title \"Sec z\", ";
   $cmd = $cmd."\"$fw\" u 1:(-0.07 *\$7 -4.7) axes x1y2 pt 5 ps 2 lc rgb \"grey\" title \"guess\", ";
   $cmd = $cmd."\"$fw\" u 1:6 axes x1y2 w li lw 3 lc rgb \"brown\" title \"Focus\", ";
   $cmd = $cmd."\"< tail -n 1 $fw\" u 1:(\$2*0+12):(sprintf(\"g=%.3f  F=%.3f\", -0.07 *\$7 -4.7, \$6)) w labels offset char -10,1 tc rgb \"blue\" notitle \' ";
   $cmd = $cmd."loop.plt";

   system $cmd;
}

