#!/usr/bin/perl -W

$fw = `ls fw*.dat | tail -n 1 | awk \'{print \$1}\'`;
chop $fw;
#print "$fw";

$cmd = "gnuplot46 -persist -e \'reset; stats \"$fw\" u 7 nooutput; ";
$cmd = $cmd."set term x11; ";
$cmd = $cmd."set title \"FFT (FWHM-FOCUS-TEMP) Monitoring\"; ";
$cmd = $cmd."set xdata time; ";
$cmd = $cmd."set timefmt \"%H:%M:%S\"; ";
$cmd = $cmd."set format x \"%H:%M\"; ";
$cmd = $cmd."set autoscale xfix; ";
$cmd = $cmd."set yrange [0:12]; ";
$cmd = $cmd."set y2tics; ";
$cmd = $cmd."set y2range [-5.8:-5.2]; ";
$cmd = $cmd."set key left top; ";
$cmd = $cmd."set xlabel \"UT ($fw)\"; ";
$cmd = $cmd."set ylabel \"FWHM (arcsec) / T (C)\"; ";
$cmd = $cmd."set y2label \"FOCUS (mm)\"; ";
$cmd = $cmd."set grid; ";
$cmd = $cmd."plot ";
$cmd = $cmd."\"$fw\" u 1:(\$7-STATS_median+7) pt 5 ps 2 lc rgb \"orange\" title \"dT\", ";
$cmd = $cmd."\"$fw\" u 1:2 pt 4 ps 2 lc rgb \"red\" title \"N\", ";
$cmd = $cmd."\"$fw\" u 1:3 pt 4 ps 2 lc rgb \"magenta\" title \"E\", ";
$cmd = $cmd."\"$fw\" u 1:4 pt 4 ps 2 lc rgb \"green\" title \"W\", ";
$cmd = $cmd."\"$fw\" u 1:5 pt 4 ps 2 lc rgb \"blue\" title \"S\", ";
$cmd = $cmd."\"$fw\" u 1:((\$8-1)*10) pt 7 ps 2 lc rgb \"red\" title \"Sec z\", ";
$cmd = $cmd."\"$fw\" u 1:6 axes x1y2 w li lw 3 lc rgb \"brown\" title \"Focus\", ";
$cmd = $cmd."\"$fw\" u 1:(-0.07 *\$7 -3.68) axes x1y2 pt 7 ps 1 lc rgb \"black\" title \"guess\" \'";
system $cmd;

print $cmd;

