#
# ISIS Server Runtime Initialization File
#
# KMTN System OSU Lab Testing
# This version uses the isisrelay on the client IC machines
# and a hub-and-spoke communications topology [rwp/osu]
#
# R. Pogge, OSU Astronomy Dept.
# pogge.1@osu.edu
# 2014 Dec 11
#
################################################################

# ISIS Server Info

ServerID   XIS
ServerPort 6660
ServerLog  /lhome/data/Logs/ISIS/isis

# List all serial ports we might use here, max 16
# Usage: TTYPort /dev/port speed
# Example: TTYPort /dev/ttyS1 9600

TTYPort /dev/ttyS0 115200

# Define any preset UDP ports we wish to ping on startup or restart, max 32

# Ping the isisrelays on all the IC machines, this reaches the VDOS ICs

UDPPort 192.168.14.102 6600
UDPPort 192.168.14.103 6600
UDPPort 192.168.14.104 6600
UDPPort 192.168.14.105 6600
UDPPort 192.168.14.106 6600
UDPPort 192.168.14.107 6600
UDPPort 192.168.14.108 6600

# Ping the caliban data-transfer agents only as needed

UDPPort 192.168.14.102 10601
UDPPort 192.168.14.103 10601
UDPPort 192.168.14.104 10601
UDPPort 192.168.14.105 10601
UDPPort 192.168.14.106 10601

# Ping the PC-TCS Agent

UDPPort 192.168.14.108 6606

# Runtime Flags

Verbose

# Instrument ID (optional and unused for anything in detail)

Instrument KMTC

