#
# ITerm Runtime Configuration File - for user mods on isis2
#
# R. Pogge, OSU Astronomy Dept.
# pogge@astronomy.ohio-state.edu
# 2009 May 6
#
# Session Info

Name ITerm Command Console # Toolbar name

# Our ID and Port number

ID   IT
Port 0      # 0 means "any free port"

# ISIS Server Info 

ISISID IS
ISISHost 192.168.139.131
ISISPort 6600

# Runtime Flags

TimeTag
LocalTime

