#!/bin/csh
#
# mods2 - start/stop/check MODS2 instrument services
#
# usage: mods2 {start|stop} {all|isis|ie|agw|imcs|tcs|env|data|gui}
#        mods2 show
#
# This script is a wrapper that runs ssh on the mods2 instrument host
# for MODS2 instrument services, or locally starts mods2 data
# services.
#
# R. Pogge, OSU Astronomy Dept
# pogge@astronomy.ohio-state.edu
# 2010 June 20
#
# Modification History:
#   2010 Sep 19 - added gui option to launch the control panel [rwp/osu]
#   2011 Jan 16 - minor updates and enhancements for observers [rwp/osu]
#   2013 Jan 25 - added ie4x support for the lab (hidden) [rwp/osu]
#
#---------------------------------------------------------------------------

# MODS2 instrument server host

#set mods2Host = mods2
#set mods2Host = 192.168.139.230  # LBTO
set mods2Host = 172.16.1.15  # OSU Lab

# Usage message 

set usage = "mods2 {start|stop} {all|isis|ie|agw|imcs|modsUI|lbttcs|env|disp}\n       mods2 {show|status}\n"

# Process the command-line arguments

if ($#argv == 1) then
   switch ($1)
   case 'show':
   case 'status':
      ssh ${mods2Host} mods2 $1
      chkisis
      breaksw

   default:
      printf "\nERROR: unrecognized directive ${1}\n"
      printf "Usage: $usage\n"
      exit 1
      breaksw
   endsw

else if ($#argv == 2) then
   switch ($2)

   case 'all':
      printf "\nThe ${1} all directive is not yet enabled, sorry.\n"
      printf "coming soon...\n"
      exit 1
      breaksw

   # These directives are executed on mods2Host

   case 'ie':
   case 'mmc':
   case 'agw':
   case 'imcs':
   case 'lbttcs':
   case 'tcs':
   case 'modsUI':
   case 'gui':
      ssh -f ${mods2Host} mods2 $1 $2
      breaksw

   # These directive are executed locally

   case 'isis':
      if (${1} == 'stop') then
         stopisis
      else if (${1} == 'start') then
         startisis
      else
         printf "\nERROR: Unrecognized directive ${1} ${2}\n"
	 printf "Usage: ${usage}\n"
         exit 1
      endif
      breaksw

   case 'env':
   case 'modsenv':
      if (${1} == 'stop') then
	 stopagent modsenv
      else if (${1} == 'start') then
         startagent modsenv
      else
         printf "\nERROR: Unrecognized directive ${1} ${2}\n"
	 printf "Usage: ${usage}\n"
         exit 1
      endif
      breaksw

   # This starts/stops both caliban agents.  On a stop, it does a hard
   # takedown of all running CB agents

   case 'caliban':
      if (${1} == 'stop') then
	 stopagent cb_blue
         stopagent cb_red
	 killall caliban
      else if (${1} == 'start') then
         cb_blue &
         cb_red &
      else
         printf "\nERROR: Unrecognized directive ${1} ${2}\n"
	 printf "Usage: ${usage}\n"
         exit 1
      endif
      breaksw

   # Start/Stop the Red Caliban Agent

   case 'cb_red':
      if (${1} == 'stop') then
         stopagent cb_red
	 set foo = `ps h -C caliban | grep red`
	 kill -9 $foo[1]
      else if (${1} == 'start') then
         cb_red &
      else
         printf "\nERROR: Unrecognized directive ${1} ${2}\n"
	 printf "Usage: ${usage}\n"
         exit 1
      endif
      breaksw 

   # Start/Stop the Blue Caliban Agent

   case 'cb_blue':
      if (${1} == 'stop') then
         stopagent cb_blue
	 set foo = `ps h -C caliban | grep blue`
	 kill -9 $foo[1]
      else if (${1} == 'start') then
         cb_blue &
      else
         printf "\nERROR: Unrecognized directive ${1} ${2}\n"
	 printf "Usage: ${usage}\n"
         exit 1
      endif
      breaksw 

   # Start/Stop the MODS2 ds9 auto displays

   case 'disp':
      if (${1} == 'stop') then
         modsds9 1 stop
      else if (${1} == 'start') then
         modsds9 1 start
      else
         printf "\nERROR: Unrecognized directive ${1} ${2}\n"
	 printf "Usage: ${usage}\n"
         exit 1
      endif
      breaksw 

   # Start/Stop the Lab 4-wide box IE server 
   case 'ie4x':
      if (${1} == 'stop') then
	 4xIE stop
      else if (${1} == 'start') then
         4xIE start
      else
         printf "\nERROR: Unrecognized directive ${1} ${2}\n"
	 printf "Usage: ${usage}\n"
         exit 1
      endif
      breaksw

   default:
      printf "\nERROR: Unrecognized directive ${1} ${2}\n"
      printf "Usage: $usage\n" 
      breaksw

   endsw
else
   printf "\nUsage: $usage\n"
endif

exit 0
      
