#
# Caliban Runtime Initialization File
#
# Linux/SCSI version, v3.2.0
# ISIS network server interface
# MDM Observatory
#
# R. Pogge, OSU Astronomy Dept.
# pogge@astronomy.ohio-state.edu
# Modified: 2005 August 26   
#
# FOR KMTN "Spare" IC
#
LOCAL_HOST SP.CB
LOG_FILE_NAME /lhome/data/Logs/Caliban/Caliban.log
#
# data-transfer disk server interface
# uses the ISIS server network socket for communications
# We can be either a WC+IC or IC-only system.  Select
# DISK_HOST accordingly
#
#DISK_HOST WC
DISK_HOST SP.IC
DISK_INTERFACE SOCKET
#
# Serial Port info
#
# none in this config
#SERIAL_PORT /dev/ttyS1
#SERIAL_HOST WC
#
# ISIS Server Info
#
SERVER_HOST SP.IS
SERVER_IP localhost
SERVER_PORT 6600
#
# Caliban network client port
#
LOCAL_PORT 10601
#
# Data Transfer Disks
#
SPOOL_DEVICE /dev/ram0
SPOOL_DEVICE /dev/ram1
#SPOOL_DEVICE /dev/sdb
#
# Local Mount Points
#
#MOUNT UNIX:\CB\/lhome/data
#MOUNT UNIX:\CB\/mnt/electrondata
MOUNT UNIX:\CB\/mnt/ICSdata

#
# Post-processing functions
#
# Data Logging
#
ADDFITS
DOAUTOLOG
AUTOLOG_CMD /lhome/obspkg/bin/autologger %s
#
# future expansion if we setup archiving at MDM
#
# DOARCHIVE
# ARCHIVE_CMD lpr -Pbits -s %s
#
# additional runtime configuration settings
#
BLOCK_SIZE 8192
MAX_XFER_FILES 150
DBG_HEADLNG 32
DBG_DATALNG 8542
TIMEOUT 150
ACKSWAP
#
# uncomment these for engineering, or
# set interactively with +verbose and +debug
#
VERBOSE
#DEBUG
#
