#
# Makefile for XISIS v2
#
# Build the package using the "build" script not with make.
#
# We now compile with the much stricter g++ compiler instead of gcc.
#
# Version 2 now introduces date-based logging and daemon modes
#
# R. Pogge, OSU Astronomy Dept.
# pogge@astronomy.ohio-state.edu
#
# Notes:
#   Version 2 was started 2009 Mar 18 [rwp/osu]
#   Version 2.6.x is the first to include the isisd daemon version [rwp/osu]3
#
VERSION     = 2.7.3
# MODS root directory
ROOTDIR = /lhome/dts
# Directory for installed "public" binaries
BINDIR = ../bin
######################################
CC          = /usr/bin/g++
AR          = /usr/bin/ar
INCDIR      = $(ROOTDIR)/include
#
CFLAGS      = -w -c
VFLAGS      = -DISIS_VERSION='"$(VERSION)"' -DISIS_COMPDATE='"$(COMPDATE)"' \
              -DISIS_COMPTIME='"$(COMPTIME)"' -DISIS_CONFIG='"$(CONFIG)"' \
              -DISIS_LOGS='"$(LOGS)"' -DISIS_DCONFIG='"$(DCONFIG)"'
LIBS        = -I$(INCDIR) -lreadline -lhistory -lncurses
LFLAGS      = -o xisis

#
OBJS        = interfaces.o messages.o commands.o serverlog.o \
              clients.o loadconfig.o utils.o
#
.c.o:       xisisserver.h 
	    $(CC) $(CFLAGS) $(VFLAGS) $*.c
#
all:        xisis.a xisis 
#
xisis.a:  $(OBJS) 
	    /bin/rm -f  xisis.a
	    $(AR) cr xisis.a $(OBJS)
	    ranlib xisis.a
#	    \cp xisis.a $(ROOTDIR)/ulib
#
# Interactive ISIS server
#
xisis:	    xisis.a xisisserver.h 
	    $(CC) $(VFLAGS) $(LFLAGS) main.c xisis.a $(LIBS)
#	    \cp xisis ../bin
#
clean:
	    /bin/rm -f xisis xisis.a *.o

install:
	    \cp xisis $(BINDIR)/
#	    \cp isisd $(BINDIR)/
	    /bin/rm -f *.o
