#
# ISIS port relay config file
#
# KMT System Configuration
#
# R. Pogge, OSU Astronomy Dept.
# pogge.1@osu.edu
# 2014 Oct 9
#
################################################################

# UCP Socket info (localhost is implicit)

UDPPort 6600 

# TTY Port info
# This is a hardwired physical port 

TTYPort /dev/ttyS0
Speed 9600
DataBits 8
StopBits 1
Parity 0

# ISIS Server Info 

# This is the KMT system executive ISIS server

ISISHost 192.168.13.109
ISISPort 6660

# Relay Application Runtime flags 

VERBOSE
#nolog
#debug
