#
# ITerm Runtime Configuration File
#
# R. Pogge, OSU Astronomy Dept.
# pogge@astronomy.ohio-state.edu
# 2014 December 11
#
# Session Info

Name KMTN ITerm Console # Toolbar name

# Our ID and Port number

ID   KMT.IT
Port 0      # 0 means "any free port"

# KMTN System Executive ISIS Server

ISISID XIS
ISISHost 192.168.13.109
ISISPort 6660

# Default remote host is the ICS detector control computer

RemHost ICS

# Runtime Flags

TimeTag
LocalTime
