#
# XISIS Server Runtime Initialization File
#
# MODS1 OSU Lab Testing Configuration
#
# R. Pogge, OSU Astronomy Dept.
# pogge@astronomy.ohio-state.edu
# 2009 June 30
#
################################################################

# XISIS Server Info

ServerID   XIS
ServerPort 6660
ServerLog  /lhome/data/Logs/XISIS/xisis

# List all serial ports we might use here, max 8
# Comment out any unused ports to avoid startup errors

#TTYPort /dev/ttyD0
#TTYPort /dev/ttyD1
#TTYPort /dev/ttyD2
#TTYPort /dev/ttyD3
#TTYPort /dev/ttyS0
#TTYPort /dev/ttyUSB0

TTYPort /home/dts/VMFolder/socat/pty/ISISLink
TTYPort /home/dts/VMFolder/socat/pty/ISISLink2

# Define any preset UDP ports we wish to ping on startup or restart, max 8

# MODS1 Lab Testing: 
#  M1.IE on mods1 (172.16.1.14) port 10700
#  M1.IE on mods3 (172.16.1.140) port 10700
#  Caliban Agents: M1.CB and M1.CR on isis5, ports 10601 and 10602
#  LBTTCS Agent: TC on isis5, port 10801

#UDPPort 172.16.1.14 10700
#UDPPort 172.16.1.140 10700
#UDPPort 172.16.1.85 10801
#UDPPort 172.16.1.85 10601
#UDPPort 172.16.1.85 10602
#Can we ping to ISIS on other machines?
UDPPort 192.168.15.102 6600
UDPPort 192.168.15.103 6600
UDPPort 192.168.15.104 6600
UDPPort 192.168.15.105 6600
UDPPort 192.168.15.106 6600
UDPPort 192.168.15.107 6600
UDPPort 192.168.15.108 6600
#UDPPort 192.168.15.109 6600
#UDPPort 192.168.15.110 6600



# Runtime Flags

Verbose

# Instrument ID (optional)

Instrument KMTC

