#
# ttytool runtime config file
#
# R. Pogge, OSU Astronomy Dept.
# pogge@astronomy.ohio-state.edu
# 2005 February 17
#
################################################################

# ttytool's ISIS client info (Host=localhost is implicit)

ID   TTY
Port 10701

# Application Mode: either STANDALONE or ISISclient

Mode Standalone
#Mode ISISclient

# ISIS Server Info - only releveant if Mode=ISISclient

ISISID   IS
ISISHost darkstar
ISISPort 6600

# Serial (TTY) port parameters

#TTYPORT 172.16.1.56:8001
TTYPORT 172.16.1.63:8000

#TTYPORT /dev/cua0
#SPEED 9600
#DATABITS 8
#STOPBITS 1
#PARITY 0

# ttytool client application runtime flags

VERBOSE
#nolog
#debug
