#
# KMTNet TCS Agent runtime config file
#
# Note that while mixed cases are used for readability, entries
# are case insensitive *EXCEPT* for network hostnames or Unix
# filenames.  Beware!
#
# R. Pogge, OSU Astronomy Dept.
# pogge@astronomy.ohio-state.edu
# 2005 May 27 (Original version - Yale1m)
#
# S. Cha, KASI KMTNet team
# chasm@kasi.re.kr
# 2014 April 1 (KMTNet version)
# 
# - System: OSU Dev.sys
# - last update: 2014-12-12 [rwp/osu]
#
# - System: KMTNet-SSO-Standalone (KMTNA-STA)
# - last update: 2015-10-17 [sc/kasi]
#
###########################################################################

# Application Mode: either STANDALONE or ISISclient
Mode Standalone
#Mode ISISclient

# ISIS Server Info - only releveant if Mode=ISISclient
#ISISID    IS
#ISISHost  localhost
#ISISPort  6600
# Changed to V2 Executive ISIS Server [rwp/osu - 2014 Dec 12]
ISISID    XIS
ISISHost  192.168.15.109
ISISPort  6660

# TCS Agents ISIS client info (Host=localhost is implicit)
ID    TC.STA
Port  5755

# TCS server (PCTCS Telcom) info
TCS_Host   192.168.15.60 (KMTNA)
TCS_Port   5750
TCS_TelID  KMTNET
TCS_SysID  TCS

# AUX control server info
AUX_Host   192.168.15.60 (KMTNA)
AUX_Port   5752
AUX_TelID  KMTNET
AUX_SysID  AUX

# Telescope ID for FITS Header input
FITS_TelID  KMTA  [sc/kasi - 2015 Feb 12]

# Timeout setting for Telcom tcp and PC-TCS serial link (in second)
Timeout_PCTCS   5
Timeout_Telcom  8  [sc/kasi - 2014 Dec 23]

# TCS & AUX telemetry update & status logging interval (in second)
UpdateInt_TCS    1.0
UpdateInt_AUX    0.2
LoggingInt_TCS  30.0
LoggingInt_AUX  30.0

# TCS & AUX telemetry update interval (in second)
UpdateInt_TCS  1.0
UpdateInt_AUX  0.2

# TCS & AUX TCP Links auto recovery mode setting (on/off)
AutoRecovery_TCS  on
AutoRecovery_AUX  on

# TCS & AUX TCP Links auto recovery try interval (in seconds)
ArcInt  2.0

# HW configuration (updated on 2014-09-28 for CTIO telescope)
TCS_Guide_Step_RA      0.00503608  (in arcsec/encoder_count)
TCS_Guide_Step_Dec     0.01321939  (in arcsec/encoder_count)
TCS_Guide_MinOff_RA    0.01        (in arcsec, minimum RA guiding offset)
TCS_Guide_MinOff_Dec   0.02        (in arcsec, minimum rDec guiding offset)
AUX_FS_Filter_OpTime  14.5         (in seconds, filter slide operation time)
AUX_FS_Shutter_OpTime  5.2         (in seconds, camera shutter opening time)
AUX_FA_ActNum_South    2           (south actuator number)
AUX_FA_ActNum_East     1           (east actuator number)
AUX_FA_ActNum_West     3           (west actuator number)

# TCS Agent client/agent application runtime flags (on/off)
VERBOSE     off
DEBUG       off
DOLOG       on    (event log option)
VERLOG      on    (verbose log)

# TCS Agent log/output/import file path
LOGFILE  /data/Logs/TC/tc             (default)
CATFILE  /home/dts/catalog/pctcs.cat  (default for init.importing)

# END
