#
# tvdisp client runtime config file
#
# R. Pogge, OSU Astronomy Dept.
# pogge@astronomy.ohio-state.edu
# 2005 May 13
#
################################################################

# tvdisp's ISIS client info (Host=localhost is implicit)

ID   TV
Port 10901

# Application Mode: either STANDALONE or ISISclient

Mode Standalone
#Mode ISISclient

# ISIS Server Info - only releveant if Mode=ISISclient

ISISID   IS
ISISHost 172.16.1.240
ISISPort 6600

# Display parameters

AppName xtv
WinName Y4KCam Image Display
NCols  800
NRows  800
NColors 256
Zoom 4
#Flip
#IBW

# Client Runtime flags 

VERBOSE
#nolog
#debug
