###########################################################################
#
# KMTNet OBS Agent runtime config file
#
# Note that while mixed cases are used for readability, entries
# are case insensitive *EXCEPT* for network hostnames or Unix
# filenames.  Beware!
#
#   R. Pogge, OSU Astronomy Dept.
#   pogge@astronomy.ohio-state.edu
#   2004 Feb 17 (TCSAgent original version - agent pctcs for Yale1m v3.3.1)
#
#   S. Cha, KASI KMTNet team
#   chasm@kasi.re.kr
#   2014 Apr  1 (TCSAgent KMTNet version)
#   2016 Sep 20 (OBSAgent for KMTNet system)
#
# - Copied from ini/pctcs.kmtnc.ini & Initionally modified for OBS Agent
#
# - Optimized to KMTNet-SAAO
# - Updated on 2023-06-14 by S. Cha
#
###########################################################################

## Application Mode: either STANDALONE or ISISclient

#Mode Standalone
Mode ISISclient

## ISIS Server Info - only releveant if Mode=ISISclient
## Changed to V2 Executive ISIS Server [rwp/osu - 2014 Dec 12]

ISISID    XIS
ISISHost  192.168.13.109
ISISPort  6660

## OBS Agents ISIS client info (Host=localhost is implicit)

ID    OBS
Port  6650

## System specification and TCS limit position configuration

# SAAO instrument control system settings
ICS_DATASOURCE   ADC

# SAAO Telescope position
TCS_LATITUDE         -32.378861    # deg N  ( -32:22:43.9)
TCS_LONGITUDE        339.189556    # deg W  ( -20:48:37.6)
TCS_ELEVATION       1748           # meter

# SAAO TCS pointing/tracking tolerance
 TCS_TOLERANCE_POINTING     0.2   # arc-sec, increasing when try num increasing
#TCS_TOLERANCE_POINTING     2.0   # adjusted tomporary: 0.2 --> 2.0 on 2023.00
 TCS_TOLERANCE_TRACKING     0.5   # arc-sec
#TCS_TOLERANCE_TRACKING     1.0   # adjusted tomporary: 0.5 --> 1.0 on 2023.00
 TCS_UNSTABLE_HYSTERESIS    2     # for checking RA/DEC axes oscillation (Typ. 2-3)
 ## Note: adjust TCS_TOLERANCE_POINTING in case frequent "failed to point at the RA / the DEC or Both RA/DEC"
 ## Note: adjust TCS_TOLERANCE_TRACKING in case frequent "failed to point due to OSCILLATION .."

# SAAO TCS limit configuration updated in 2015.11
TCS_LIMIT_HA           4.60    # hour (04:36:00)
TCS_LIMIT_DEC_N      +21.00    # deg  (Alt 36.8 on Merdian)
TCS_LIMIT_DEC_S      -85.50    # deg  (Alt 36.8 on Merdian)
TCS_LIMIT_SECZ         2.37    # secZ (Alt=25)
TCS_LIMIT_ALT         30.00    # deg  (Alt=30)
TCS_LIMIT_WARNING      1.25    # deg  (5 min)

## TCS Agent client/agent application runtime flags (on/off)

VERBOSE     off    # display verbose message on console
DEBUG       off    # display debug message on console
DOLOG       on     # log event messages on the 'event' log
DBGLOG      on     # log debugging messages on the 'debug' log, making another log file for debugging log
OBSLOG      on     # log script obs results on the 'scrobs' log, making another log file for script obs log
LOGVER      on     # log verbose messages on the 'event' log
TIMETAG     on     # time tag display on console

## TCS Agent log/output/import file path

LOGFILE  /data/Logs/OBS/obs           # default, directory and prefix of log files
#SCRIPT  /data/osc/default.osc        # default for initialy loading
#SCRIPT  /home/dts/osc/default.osc    # default for initialy loading
#SCRIPT  osc/test.osc                 # for test and debugging
#SCRIPT  no                           # initialy loading not used

# END
