#
# ISIS server ini file for ANDICAM
#
# This is for an ISIS server running on 
# host "andicam" for the ANDICAM at the
# CTIO 1.3m (SMARTS operations)
#
# R. Pogge, OSU Astronomy Dept.
# pogge@astronomy.ohio-state.edu
# 2003 January 30
#
################################################################

# ISIS server on the andicam data-taking host

ServerID   IS
ServerPort 6600
#ServerLog  /data/Logs/ISIS/isis.log
ServerLog  /home/observer/Logs/isis.log
#Verbose

# WC MS-DOS PC is connected via a serial port

TTYPort /dev/ttyS0

# Instrument 

Instrument ANDICAM
