#!/bin/csh
#

setenv CDATE `date +'%Y-%b-%d'`
setenv CTIME `date +'%T'`
setenv ISCFG /lhome/dts/Config/isis.ini
setenv ISDCFG /lhome/dts/Config/isisd.ini
setenv ISLOG /lhome/data/Logs/ISIS/isis

make -f Makefile.build clean
make -f Makefile.build "COMPDATE=$CDATE" "COMPTIME=$CTIME" "CONFIG=$ISCFG" "LOGS=$ISLOG" "DCONFIG=$ISDCFG"
/bin/rm *.o
exit
